### ISSUE TITLE
Please put up the latest version on npm

### ISSUE THREAD

**Issue by cdelguercio** [Paldom/angular2-rest#10]
The current version doesn't work and throws: "ORIGINAL EXCEPTION: TypeError: observable.map is not a function" when I try to call my REST endpoint, but if I copy and paste the most recent angular2-rest.ts file and compile it then it works fine.

**Comment by freezy** [comment]
Until it's updated, you can put `Paldom/angular2-rest` instead of a version in your `package.json` and npm will take the latest commit from master.
