### ISSUE TITLE
Abandoned Project?

### ISSUE THREAD

**Issue by jspizziri** [Paldom/angular2-rest#24]
@Paldom,

Is this project now abandoned? If so, is there anyone other than you who has commit access to keep the project going? Or should it be forked and moved forward somewhere else.

**Comment by dimkk** [comment]
as far as I see, this branch has some short term updates, I will try it soon https://github.com/DanielKucal/angular2-rest/network

**Comment by hboylan** [comment]
Created [this](https://github.com/hboylan/ng2-http) module using @Paldom's awesome original.
