### ISSUE TITLE
hi,like $resource in angular1 

### ISSUE THREAD

**Issue by ghost** [Paldom/angular2-rest#4]
hi,there
thank you 
i need this  
I need it to replace $resource  

:)

good job

i used django-rest-framework （django-rest-framework.org）
It can work it ?
thank you very much ,paldom

**Comment by iloveyo123u1** [comment]
i used django-rest-framework （django-rest-framework.org）
It can work it ?
thank you very much ,paldom

**Comment by Paldom** [comment]
Hi @iloveyo123u1,
thanks :) it should work with any rest fw, but there could be some mistakes with merged contributions, I cant confirm them yet. Look at the very first commits, I used that version in production with a NodeJS backend. Automatic tests are on the way to solve this ;)
